name: Release

on:
  push:
    tags:
      - 'v*' # Trigger on tags starting with 'v' (e.g., v1.2.3)

jobs:
  build-and-publish:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ["3.9", "3.10", "3.11"]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Important for Hatch versioning

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install hatch hatchling

      - name: Build NAR
        run: hatch build -t custom

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*.nar
